# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WtyczkaQGISDialog
                                 A QGIS plugin
 wtyczka do rpostych obliczeń geodezyjnych
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-20
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Miłosz Meller
        email                : 01160182@pw.edu.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.utils import iface
from qgis.core import QgsWkbTypes
import numpy as np
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QDialog, QApplication, QMessageBox

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'wtyczka_qgis_dialog_base.ui'))


class WtyczkaQGISDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(WtyczkaQGISDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.oblicz.clicked.connect(self.dane)
        
            
    def dane(self):
        warstwa = self.mMapLayerComboBox.currentLayer()
        ilosc = warstwa.featureCount()
        aktywna = iface.activeLayer()
        ilosc = aktywna.selectedFeatureCount()
        x = []
        y = []
        h = []
        nr = []
        for punkt in aktywna.selectedFeatures():
            x.append(punkt['x92'])
            y.append(punkt['y92'])
            h.append(punkt['h']) 
            nr.append(punkt['nr'])   
                
        if ilosc == 0 or ilosc == 1:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText('Zaznacz 2 punkty, aby policzyć różnicę wyskosci lub 3, aby policzyć pole.')
            msg.setInformativeText
            msg.setWindowTitle("Za mało danych")
            msg.exec_()
            
        if ilosc == 2:
            dh = h[1] - h[0]
            iface.messageBar().pushMessage('Różnica wysokosci jest równa: '+str(round(dh,3))+' [m]')
        if ilosc > 2: 
            pts = []
            for i in range(0, len(x)):
                pts.append([x[i], y[i]])
            pa = 0
            for i in range(len(pts)):
                if i == len(pts)-1:
                    pa = pa + (pts[i][0] + pts[0][0]) * (pts[i][1] - pts[0][1])
                else: 
                    pa = pa + (pts[i][0] + pts[i+1][0]) * (pts[i][1] - pts[i+1][1])

            P = abs(pa/2)
            iface.messageBar().pushMessage('Pole ' + str(nr)+ ' jest równe: '+str(P)+' [m2]')
        if ilosc > 4:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText('Zaznacz 2 punkty, aby policzyć różnicę wyskosci lub 3, aby policzyć pole.')
            msg.setInformativeText
            msg.setWindowTitle("Za dużo danych")
            msg.exec_()
              